# Generated by Django 3.0.14 on 2022-07-01 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('team_short_name', models.CharField(default='XXX', max_length=3)),
                ('team_logo', models.ImageField(blank=True, null=True, upload_to='team_logo/')),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('team_point', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_coach', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('eligibility_status', models.CharField(choices=[('eligible', 'Eligible'), ('retired', 'Retired'), ('ineligible', 'Ineligible'), ('injured', 'Injured')], default='eligible', max_length=20)),
                ('team_role', models.CharField(choices=[('captain', 'Captain'), ('vice_captain', 'Vice Captain'), ('none', 'None')], default='none', max_length=20)),
                ('squad_position', models.CharField(choices=[('wicketkeeper', 'WicketKeeper'), ('batsman', 'Batsman'), ('bowler', 'Bowler'), ('allrounder', 'AllRounder')], default='allrounder', max_length=20)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team', to='iplapp.Team')),
            ],
        ),
    ]
