# Generated by Django 3.0.14 on 2022-07-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='team_logo',
        ),
    ]
