# Generated by Django 3.0.14 on 2022-07-13 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iplapp', '0002_remove_team_team_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground_name', models.CharField(max_length=50)),
                ('active_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('street', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
                ('owner_org', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_day', models.DateField(default=django.utils.timezone.now)),
                ('match_start_time', models.TimeField(default=django.utils.timezone.now)),
                ('match_end_time', models.TimeField(default=django.utils.timezone.now)),
                ('match_status', models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('full_time', 'Full Time'), ('cancelled', 'Cancelled'), ('abandoned', 'Abandoned')], default='scheduled', max_length=20)),
                ('home_team_score', models.IntegerField(default=0)),
                ('guest_team_score', models.IntegerField(default=0)),
                ('referee_comments', models.TextField(null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('ground', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_ground', to='iplapp.Ground')),
                ('guest_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_guest_team', to='iplapp.Team')),
                ('home_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_home_team', to='iplapp.Team')),
                ('match_referee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_referee', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'matches',
            },
        ),
    ]
