# Generated by Django 3.0.14 on 2022-07-13 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iplapp', '0004_playerstats'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLrole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Coach', 'Coach'), ('Scorer', 'Scorer')], max_length=20)),
                ('receiver_name', models.CharField(max_length=50)),
                ('receiver_email', models.EmailField(max_length=100)),
                ('registered', models.CharField(default='No', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='team_state',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
